### ISSUE TITLE
Weathermap permissions management errors

### ISSUE THREAD

**Issue by ogomezod** [thurban/plugin_weathermap#111]
Hello,

When revoking permissions from the web interface of cacti within each of the weathermaps to any of the users are removed from the permissions table, instead of leaving the user with the flag Allowed to not permitted. Once the user disappears from that table it is no longer possible to manage map access permissions from the web interface.
Would anyone who has had the same problem know how to solve it?

Link to cacti forum: [Weathermap permissions management errors](https://forums.cacti.net/viewtopic.php?t=62625)

Thanks and best regards.

**Comment by TheWitness** [comment]
I need you to upload a screen2gif of what you are doing.  From the beginning to the end.

**Comment by TheWitness** [comment]
Never mind.  I see it now.

**Comment by TheWitness** [comment]
Okay, should be fixed now.  Let me know what you find.

**Comment by ogomezod** [comment]
It is working fine now. Thanks for fixing it so quickly.

**Comment by TheWitness** [comment]
Wasn't that quick.  Been super busy though.

**Comment by arno-st** [comment]
Sorry to bother you, but this is still not working with the latest dev branch.

**Comment by TheWitness** [comment]
@arno-st please open a new ticket.
