### ISSUE TITLE
Undefined variable: newtine 

### ISSUE THREAD

**Issue by jdcoats** [thurban/plugin_weathermap#55]
change to newtime
```

2023/01/18 08:38:18 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php[695]:process_poller_output(), /lib/poller.php[706]:process_poller_output(), /lib/poller.php[687]:api_plugin_hook_function(), /lib/plugins.php[149]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[270]:weathermap_poller_output(), /plugins/weathermap/setup.php[1066]:CactiErrorHandler())
2023/01/18 08:38:18 - ERROR PHP NOTICE in Plugin 'weathermap': Undefined variable: newtine in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/setup.php on line: 1066
```

**Comment by TheWitness** [comment]
👍

**Comment by TheWitness** [comment]
Okay, fixed in my branch.

**Comment by jdcoats** [comment]
Haha, that one could be done with one eye open

**Comment by TheWitness** [comment]
My cup just runnith empty.  Back to the kitchen.

**Comment by jdcoats** [comment]
so i figured if you're working it i would also. I did the #57 fix but now can see that some images still have the iCCP chunk 
```
2023/01/18 20:46:23 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[825]:api_plugin_hook(), /lib/plugins.php[83]:api_plugin_run_plugin_hook(), /lib/plugins.php[225]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1111]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[420]:WeatherMap->DrawMap(), /plugins/weathermap/lib/WeatherMap.class.php[3549]:WeatherMapNode->pre_render(), /plugins/weathermap/lib/WeatherMapNode.class.php[487]:imagecreatefromfile(), /plugins/weathermap/lib/WeatherMap.functions.php[475]:imagecreatefrompng(), CactiErrorHandler())
2023/01/18 20:46:23 - ERROR PHP WARNING in Plugin 'weathermap': imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/lib/WeatherMap.functions.php on line: 475
```
I will fix myself with mogrify *.png and check them
This may be related to part 2 of #56 and me manually copying all of the images from images to images/objects myself.

```
/var/www/localhost/htdocs/cacti/plugins/weathermap # mogrify images/*.png
/var/www/localhost/htdocs/cacti/plugins/weathermap # mogrify images/objects/*.png

resolved this

**Comment by jdcoats** [comment]
Im still getting some weathermap warning s but will look into that tomorrow to see what has changed.
weathermap is far more noisy in the logs than i'm used to on a single polling cycle.
```
2023/01/18 20:54:27 - SYSTEM INTROPAGE STATS: Time:6.49, Checks:74, Details:74, Trends:5
--
2023/01/18 20:54:24 - SYSTEM DSSTATS STATS: Time:3.53 Type:HOURLY
2023/01/18 20:54:24 - SYSTEM SYSLOG STATS: Time:0.12 Deletes:0 Incoming:266 Removes:116 XFers:0 Alerts:71 Alarms:0 Reports:0
2023/01/18 20:54:24 - SYSTEM STATS: WEATHERMAP Time:1.57 Maps:10 Warnings:20 Notes:None
2023/01/18 20:54:24 - WEATHERMAP MAPSTATS Time:0.11 MapId:1 MapFile:BixWP.conf Warnings:0
2023/01/18 20:54:24 - WEATHERMAP MAPSTATS Time:0.17 MapId:2 MapFile:Campus.conf Warnings:0
2023/01/18 20:54:24 - WEATHERMAP MAPSTATS Time:0.17 MapId:3 MapFile:Connectivity.conf Warnings:0
2023/01/18 20:54:23 - WEATHERMAP MAPSTATS Time:0.18 MapId:4 MapFile:Datacenter.conf Warnings:0
2023/01/18 20:54:23 - WEATHERMAP MAPSTATS Time:0.07 MapId:5 MapFile:ExternalASA.conf Warnings:0
2023/01/18 20:54:23 - WEATHERMAP MAPSTATS Time:0.17 MapId:6 MapFile:MAN.conf Warnings:0
2023/01/18 20:54:23 - WEATHERMAP MAPSTATS Time:0.21 MapId:7 MapFile:Mustian.conf Warnings:0
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: ReadData: LINK BIXLER-Mustian-Distroa, target: /var/www/localhost/htdocs/cacti/rra/775/1959.rrd on config line 384 of /var/www/localhost/htdocs/cacti/plugins/weathermap/configs/Mustian.conf had no valid data, according to WeatherMapDataSource_rrd
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: Target /var/www/localhost/htdocs/cacti/rra/775/1959.rrd doesn't exist. Is it a file? [WMRRD06]
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/775/1959.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/775/1959.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: ReadData: LINK BIXLER-Mustian-Distro, target: /var/www/localhost/htdocs/cacti/rra/775/11685.rrd on config line 375 of /var/www/localhost/htdocs/cacti/plugins/weathermap/configs/Mustian.conf had no valid data, according to WeatherMapDataSource_rrd
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: Target /var/www/localhost/htdocs/cacti/rra/775/11685.rrd doesn't exist. Is it a file? [WMRRD06]
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/775/11685.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/775/11685.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: ReadData: LINK Mustian-Distro-TMH, target: /var/www/localhost/htdocs/cacti/rra/775/1958.rrd on config line 276 of /var/www/localhost/htdocs/cacti/plugins/weathermap/configs/Mustian.conf had no valid data, according to WeatherMapDataSource_rrd
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: Target /var/www/localhost/htdocs/cacti/rra/775/1958.rrd doesn't exist. Is it a file? [WMRRD06]
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/775/1958.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:23 - WEATHERMAP WARNING: [Map 7] Mustian.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/775/1958.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:23 - WEATHERMAP MAPSTATS Time:0.12 MapId:8 MapFile:POBs.conf Warnings:0
2023/01/18 20:54:23 - WEATHERMAP MAPSTATS Time:0.17 MapId:9 MapFile:TMH.conf Warnings:0
2023/01/18 20:54:22 - WEATHERMAP WARNING: [Map 9] TMH.conf: ReadData: LINK H-GC-45-MAIN-CORE-7009-01, target: /var/www/localhost/htdocs/cacti/rra/154/2232.rrd on config line 400 of /var/www/localhost/htdocs/cacti/plugins/weathermap/configs/TMH.conf had no valid data, according to WeatherMapDataSource_rrd
2023/01/18 20:54:22 - WEATHERMAP WARNING: [Map 9] TMH.conf: Target /var/www/localhost/htdocs/cacti/rra/154/2232.rrd doesn't exist. Is it a file? [WMRRD06]
2023/01/18 20:54:22 - WEATHERMAP WARNING: [Map 9] TMH.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/154/2232.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:22 - WEATHERMAP WARNING: [Map 9] TMH.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/154/2232.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:22 - WEATHERMAP MAPSTATS Time:0.18 MapId:11 MapFile:Wireless.conf Warnings:0
2023/01/18 20:54:22 - SYSTEM MONITOR STATS: Time:0.02 Reboots:0 DownDevices:0 Notifications:0 Purges:0
2023/01/18 20:54:22 - WEATHERMAP WARNING: [Map 11] Wireless.conf: ReadData: LINK DIST1-DIST2, target: /var/www/localhost/htdocs/cacti/rra/1960/24928.rrd on config line 230 of /var/www/localhost/htdocs/cacti/plugins/weathermap/configs/Wireless.conf had no valid data, according to WeatherMapDataSource_rrd
2023/01/18 20:54:22 - WEATHERMAP WARNING: [Map 11] Wireless.conf: Target /var/www/localhost/htdocs/cacti/rra/1960/24928.rrd doesn't exist. Is it a file? [WMRRD06]
2023/01/18 20:54:22 - WEATHERMAP WARNING: [Map 11] Wireless.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/1960/24928.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:22 - WEATHERMAP WARNING: [Map 11] Wireless.conf: RRD ReadData: poller_output: /var/www/localhost/htdocs/cacti/rra/1960/24928.rrd is not a valid RRD filename within this Cacti install. <path_rra> is /var/www/localhost/htdocs/cacti/rra [WMRRD08]
2023/01/18 20:54:22 - SYSTEM THOLD STATS: Time:1.6206 Tholds:2997 TotalDevices:1756 DownDevices:7 NewDownDevices:0
2023/01/18 20:54:21 - SYSTEM MAINT STATS: Time:0.00
2023/01/18 20:54:21 - SYSTEM STATS: Time:19.0276 Method:spine Processes:2 Threads:40 Hosts:1756 HostsPerProcess:878 DataSources:67152 RRDsProcessed:0
```

**Comment by jdcoats** [comment]
looks like those are just links i may have had broken before and just were not logged previously, more tomorrow :)

**Comment by jdcoats** [comment]
wow, so the editor does not let me select a graph? i have to manually input the file name/data source rrd?

![image](https://user-images.githubusercontent.com/42470924/213338623-b5924d1f-2751-471f-a877-ed8f5d1b0d34.png)

**Comment by jdcoats** [comment]
yeah the selector is terrible, not sure i can fix it with GUI, cant find the interfaces.

**Comment by TheWitness** [comment]
I'll have some time on Saturday to put into some of the bigger beta issues.  Wife is going with the kids shopping, which I'm not a super fan of.  I basically moved the GUI forward as best I could in the first pass, but I'm more of a database guy.  The core of the WeatherMap engine uses the config file as the reference.  So, by virtue of that, you loose (or risk to loose) some of the goodies in terms of usability from a Cacti perspective.

**Comment by TheWitness** [comment]
@jdcoats, does it provide any of the interfaces?

**Comment by TheWitness** [comment]
Also, are those RRDfile paths valid?

**Comment by jdcoats** [comment]
yes, Im not sure what is going on really, some but not all and most of the time when you select it, it just fills the box with the name and not a valid path to rrd. I did it manually by tracking down the rrd's and filling in the blanks :)

another insignificant observation is the logging is chatty even when set to quiet. My preference would be to not see the individual MAPSTATS when set to quiet :) The SYSTEM STAT WEATHERMAP alone is enough.

![image](https://user-images.githubusercontent.com/42470924/213565345-ac7c379e-b927-4a0c-9c65-2d2e5a8be0db.png)

**Comment by TheWitness** [comment]
Yea, let me look into that.  This is why we do a Beta.  I have zero or almost zero experience with this and it's only by you guys providing feedback that I can ensure that it follows the original design intent.
